### ISSUE TITLE
I got an error while adding API using composer

### ISSUE THREAD

**Issue by prasadmunna** [PaymentHighway/paymenthighway-php-lib#19]
I got an error when i add this "solinor/paymenthighwayio" : "1.6.0" and update composer

    "require" : 
    {
        "solinor/paymenthighwayio" : "1.6.0"
    }
![deepinscreenshot_select-area_20190204190307](https://user-images.githubusercontent.com/16593159/52211315-88bd3580-28af-11e9-8e67-e3feabf07364.png)

**Comment by Kostersson** [comment]
Could you please provide us following information:

1. Your composer version
2. Content of "require" in your composer.json
3. Content of "require-dev" in your composer.json
4. Paymenthighway related fields in your composer.lock

**Comment by prasadmunna** [comment]
1.My Composer version 1.7.1 
2. 
  "require": {
    "php": ">=5.6.0",
    "ramsey/uuid" : "^3.0",
    "nategood/httpful": "^0.2",
    "respect/validation": "^1.0",
    "solinor/paymenthighwayio" : "1.6"
  },

3.   "require-dev" : {
    "phpunit/phpunit" : "^4.8"
  },

4.There is no related filds with "PaymenyHighway" in lock file.

**Comment by prasadmunna** [comment]
I have one more query when i am looking the API reference from site

$transactionId = "52ea5beb-343b-4516-ab70-ede2baa058c8"; // get sph-transaction-id as a GET parameter
$amount = 2499;
$currency = "EUR";

$response = $paymentApi->commitFormTransaction($transactionId, $amount, $currency );

$response->body->result->code; // 100


**Where we can get the transactionId in the above code ?**

**Comment by prasadmunna** [comment]
Hello Kostersson, Thanks for replying. Yes, I have solved the Composer issue.

Now I am trying to commit a test payment using the PaymentAPI like 
use Solinor\PaymentHighway\PaymentApi;

$serviceUrl = "https://v1-hub-staging.sph-test-solinor.com";
$signatureKeyId = "testKey";
$signatureSecret = "testSecret";
$account = "test";
$merchant = "test_merchantId";
try{
	$paymentApi = new PaymentApi(
                    $serviceUrl,
                    $signatureKeyId,
                    $signatureSecret,
                    $account,
                    $merchant
                );

	$p_response = $paymentApi->initTransaction();

	
	    $transactionId = $p_response->body->id; // get sph-transaction-id as a GET parameter
		$amount = "2499";
		$currency = "EUR";

		$response = $paymentApi->commitFormTransaction($transactionId, $amount, $currency );

var_dump($response);die;
		$response->body->result->code; // 100
		echo $response->body->result->code;die;


}catch (Exception $e) {
					echo  $e->getMessage();die;
}


==============but i got respone body=======================

["body"]=>
--
  | object(stdClass)#29 (1) {
  | ["result"]=>
  | object(stdClass)#28 (2) {
  | ["code"]=>
  | int(902)
  | ["message"]=>
  | string(67) "Transaction 5ddba5e2-23dd-4253-8584-daa0cd69fc0d could not be found"
  | }
  | }

**Comment by Kostersson** [comment]
When using card tokens, after you have initialized the transaction, you should use `debitTransaction` to charge the card (https://dev.paymenthighway.io/?php#charge-a-card).

**Comment by prasadmunna** [comment]
Hello Pauli Kostamo,
I am confusing, could you please help me, Actually I want to integrate PaymentHighway for our hybrid mobile App and we will take payment using "credit cards and MobilePay", so what is better to use "Form API" or "Payment API".

So, could you explain steps we need to do that payment suing PaymentHighway?

**Comment by Kostersson** [comment]
When storing cards or using MobilePay (or creating single card payment without storing the card), you should use Form API. Payment API can be used only for charging stored cards (card tokens).

**Comment by prasadmunna** [comment]
Thanks, Pauli Kostamo
let me look at form API step by step, and any query I will let you know.
