### ISSUE TITLE
Transaction class constructor expects Splitting to be in Request namespace

### ISSUE THREAD

**Issue by nkoo** [PaymentHighway/paymenthighway-php-lib#20]
We're using library version 1.6.0. Our static code analysis tool picked up the following error

```
ERROR: InvalidArgument - PaymentHighway.php:144:75 - 
Argument 6 of Solinor\PaymentHighway\Model\Request\Transaction::__construct 
expects Solinor\PaymentHighway\Model\Request\Splitting|null,
null|Solinor\PaymentHighway\Model\Splitting provided
$transaction = new Transaction($token, $amount, $currency, true, null, $splitting);
```

Your `Transaction` class is namespaced with `Solinor\PaymentHighway\Model\Request` and the constructor expects to receive `Model\Request\Splitting`, but there's no `Splitting` in `Request`.  It's in `Model`, i.e `Model\Splitting`.

**Comment by Kostersson** [comment]
Namespace issue will be fixed in version 1.7.0-RC2.
